bosh: <%= p("githubrelease_exporter.bosh") %>
github-token: <%= p("githubrelease_exporter.github-token") %>
bosh-deployment: <%= p("githubrelease_exporter.bosh-deployment").to_json %>
github-release: <%= p("githubrelease_exporter.github-release").to_json %>
